name: Playwright Tests

on:
  push:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Vérifier le code depuis GitHub
      uses: actions/checkout@v2

    - name: Installer Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Installer les dépendances
      run: npm install

    - name: Exécuter les tests Playwright
      run: npm run test:playwright

    - name: Upload Allure Report
      uses: actions/upload-artifact@v2
      with:
        name: allure-results
        path: allure-results

    - name: Exécuter le serveur Allure pour générer le rapport
      run: |
        allure serve allure-results
      continue-on-error: true
